### ISSUE TITLE
Implementar uma solução de API Gateway 

### ISSUE THREAD

**Issue by gag2502** [fga-gpp-mds/2018.1-Dulce_App#115]
Para integrar módulos do sistema ao aplicativo vamos precisar de uma API Gateway como intercessora. 
Essa atividade faz parte do processo de pensamento crítico, conhecido como abordagem de Design Thinking, na fase de Desenvolvimento. 

![image](https://user-images.githubusercontent.com/15165117/38178357-87ce848c-35e7-11e8-89af-105b3f46b6e2.png)

**Comment by alvesisaque** [comment]
Essa issue foi desfeita porque durante a sprint houve mudança
