### ISSUE TITLE
Aplicar o GitHub Pages

### ISSUE THREAD

**Issue by alvesisaque** [fga-gpp-mds/2018.1-Dulce_App#123]
Os temas foram apresentados na issue [#78](https://github.com/fga-gpp-mds/agr-react-native/issues/78)

**Comment by egewarth** [comment]
https://github.com/jameshamann/jekyll-material-theme

**Comment by egewarth** [comment]
https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/

**Comment by egewarth** [comment]
Como usar:
https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/

Onde tem:
https://github.com/topics/jekyll-theme

**Comment by egewarth** [comment]
https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/
