### ISSUE TITLE
Treinamento de Arquitetura Microservice 

### ISSUE THREAD

**Issue by gag2502** [fga-gpp-mds/2018.1-Dulce_App#124]
O objetivo desse treinamento será alinhar a equipe aos conceitos a respeito do padrão arquitetural que será adotado 

**Data :** 05/04 
**Horário :** 12h25
**Local :** I7

**Comment by alvesisaque** [comment]
@gag2502  já temos data definida para esse treinamento?

**Comment by gag2502** [comment]
Sim ! Amanhã no almoço
