### ISSUE TITLE
Criar documentação para API

### ISSUE THREAD

**Issue by gag2502** [fga-gpp-mds/2018.1-Dulce_App#126]
Para facilitar a implementação da API desenvolvida , deve-se criar uma boa documentação seguindo as boas práticas inseridas na abordagem de Developer Experience.

**Comment by alvesisaque** [comment]
Gostaria de participar mais dessa, me passa umas coisas para ler?

**Comment by gag2502** [comment]
@alvesisaque Sobre API ???
