### ISSUE TITLE
Atualizar metodologia

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#137]
Atualizar todos papeis no documento de metodologia mostrando como cada papel estaria a frente do grupo, por passos.
Time;
PO;
Scrum Master;
Arquitetura;
DevOps.

**Comment by alvesisaque** [comment]
scrum master
- Chegar na produtividade máxima do time;
- passos para chegar na produtividade máxima do time;
treinamentos, risco.

**Comment by alvesisaque** [comment]
Time de desenvolvimento

O que deve ser feito e quais os objetivos que devem ser alcançados pelos membros
- time auto-organizável, 
- o time deve entender todos os processos.

**Comment by egewarth** [comment]
PO:
- Vender o produto;
- Interface cliente-equipe;
- Valor de negocio;
- Visão de negócio;
- Negociar com o time e com o cliente;
- Canvas.

**Comment by eliseuegewarth** [comment]
DevOps:
- Pipeline de desenvolvimento
    - Ambiente de desenvolvimento
    - Ambiente de testes
    - Ambiente de homologação
        - Gerar `.apk` e `.ipa`
- pipeline de completo de deploy
    - Analizar viabilidade de publicação de aplicativo nas lojas (PlayStore, AppStore)
    - Especificar que o deploy será feito a partir das tags do repositório, não da branch master
- Integração contínua

**Comment by alvesisaque** [comment]
@gag2502 comente aqui as atribuições da arquitetura

**Comment by gag2502** [comment]
Arquiteteta de Software 

* Planejamento e desenvolvimento da arquitetura que melhor atende a necessidade do projeto. 
* Tomar decisões sobre ferramentas e métodos de desenvolvimento 
* Liderar o desenvolvimento do sistema , estando um passo a frente na visão do mesmo 
* Lidar com a aplicação e o seu fluxo de dados

**Comment by gag2502** [comment]
Arquiteta de Software 

* Planejamento e desenvolvimento da arquitetura que melhor atende a necessidade do projeto. 
* Tomar decisões sobre ferramentas e métodos de desenvolvimento 
* Liderar o desenvolvimento do sistema , estando um passo a frente na visão do mesmo 
* Lidar com a aplicação e o seu fluxo de dados

**Comment by alvesisaque** [comment]
@gag2502 você é a melhor, obrigado
