### ISSUE TITLE
Treinamento React-Native

### ISSUE THREAD

**Issue by BeatrizHanae** [fga-gpp-mds/2018.1-Dulce_App#149]
Votação sobre o dia que será nosso treinamento de React-Native:

- Sexta-feira : 
   Data: 06/04
   Horário: 12:00
   Local: LDS - FGA

- Domingo:
   Data: 08/04
   Horário: período da noite
   Local: hangouts.

**Resultado :**
- Sexta-feira : 
   Data: 06/04
   Horário: 12:00
   Local: LDS - FGA

**Comment by gabibguedes** [comment]
Pra votar é só comentar?

**Comment by gabibguedes** [comment]
Eu voto na sexta

**Comment by egewarth** [comment]
voto sexta

**Comment by vitorl-s** [comment]
Domingo!

**Comment by gag2502** [comment]
@vitorl-s Sexta ... Nem sei se tem essa opção ... Mas tá aí kkk
