### ISSUE TITLE
Ambiente dockerizado para React Native

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#15]

**Comment by gag2502** [comment]
Eliseu como está aí ? 
Um pessoal de um grupo no telegram para Docker recomendaram isso : 
https://youtu.be/lDpnnTPokdA
https://github.com/MaximeD/docker-react-native

E o grupo é : @dockerbr
Ele é aberto , tem muita gente , sempre respondem então pode ir tirando dúvidas .

**Comment by eliseuegewarth** [comment]
DÉBITO TÉCNICO DA SPRINT 1.

**Comment by BeatrizHanae** [comment]
Essa semana terá treinamento React Native com o Amoedo?

**Comment by egewarth** [comment]
Sim, estará em outra issue em breve

**Comment by alvesisaque** [comment]
Esse épico será finalizado na sprint 3
