### ISSUE TITLE
Criar documento de requisitos de qualidade

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#158]
Nessa issue deve ser feito:
Documento de requisitos de qualidade.
[Exemplo](https://github.com/Desenho-2-2017/Ecom_merci/wiki/Requisitos-n%C3%A3o-Funcionais)

**Comment by BeatrizHanae** [comment]
Para melhorar a compreensão sobre requisitos:
https://www.devmedia.com.br/artigo-engenharia-de-software-3-requisitos-nao-funcionais/9525
http://www.ateomomento.com.br/o-que-e-um-requisito-nao-funcional/
https://www.devmedia.com.br/artigo-engenharia-de-software-introducao-a-engenharia-de-requisitos/8034
https://www.devmedia.com.br/artigo-engenharia-de-software-3-requisitos-nao-funcionais/9525

**Comment by fepas** [comment]
@egewarth @gag2502 Atualizei para o github pages o que foi feito até agora. Revisem e nos mandem _feedback_.

**Comment by fepas** [comment]
https://github.com/fga-gpp-mds/2018.1-Dulce_App/pull/176 Link do PR

**Comment by egewarth** [comment]
Quais as duvidas sobre os requisitos organizacionais? @fepas @BeatrizHanae

**Comment by fepas** [comment]
Tudo basicamente. Não temos muita ideia do que colocar neles.

**Comment by egewarth** [comment]
Bom, sobre os `Requisitos de entrega`:
Nós estamos seguindo a metodologia agil, então nossas entregas serão feitas em cada sprint certo?
Sobre a priorização é dificil falar pois não é feita baseada apenas na importancia dos requisitos e sim considerando a qualidade técnica da equipe.
Os prazos de entrega são meio que definidos no roadmap do projeto.

**Comment by egewarth** [comment]
Sobre os `Requisitos de Implementação`:
Estamos usando o React-Native,
folha de estilo Airbnb,
cobertura de testes 90%,
código em inglês.
Alguns desses podem entrar no `Requisitos padrões`, mas ai deixo pra vcs saberem oq é ou não, decidam.

**Comment by egewarth** [comment]
@fepas e @BeatrizHanae , duvidas sanadas?

**Comment by BeatrizHanae** [comment]
sim, obrigada.
