### ISSUE TITLE
Treinamento de testes de componentes React-Native

### ISSUE THREAD

**Issue by BeatrizHanae** [fga-gpp-mds/2018.1-Dulce_App#163]
Treinamento com o Roger Lenke sobre testes de componentes.

- Domingo
 Data: 07/04
 Horário: 18:00
 Local: por hangouts - link será enviado pelo slack.

**Comment by BeatrizHanae** [comment]
Hangouts realizado, somente com participação minha e do @EzequielDeOliveira , momentaneamente pelo @fepas

**Comment by gag2502** [comment]
@BeatrizHanae Muito Obrigada por relatar os participantes @BeatrizHanae . Isso vai nos ajudar no monitoramento dos riscos.
