### ISSUE TITLE
Remodelagem da arquitetura

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#188]
Criar diagrama de Pacotes da API;
Criar diagrama de Pacotes do App;
Remodelar arquitetura React/Redux.

**Comment by BeatrizHanae** [comment]
https://medium.com/the-web-tub/managing-your-react-state-with-redux-affab72de4b1
https://blog.getty.io/5-motivos-para-aprender-redux-6ac730f3f1f2
