### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#193]
Modularizar GitHub pages:
Abertura:
- eap.html
- tap.html
- canvas.html

Especificação:
- lexico.html
- prototipo.html
- roadmap.html
- mapa_requisitos.html
- visao.html
- arquitetura.html
- mindmap.html
- requisitos_qualidade.html

Viabilidade técnica:
- sprints.html
- sprint_0.html ... sprint_X.html
- metodologia.html
- metricas_indicadores.html

**Comment by alvesisaque** [comment]
Para a execução dessa tarefa, vocês devem procurar e avaliar como os grandes projetos organizam suas pastas e documentos.
A página inicial deve conter informações do produto, nada de ferramentas e equipe.

**Comment by alvesisaque** [comment]
Meninas, a idéia do léxico é que em todo o pages, todas as palavras que estão nele deve ser um link para o léxico
