### ISSUE TITLE
Corrigir erros do ESLint

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#194]
Nessa issue deve ser feito:

Correção de erros do ESLint.
Como rodar:
- `npm run lint`

Critérios de aceitação desta issue:
- [ ] Correção de todos os problemas retornados pelo comando `npm run lint`
- [ ] Build do Travis continuar estável e funcionando.

**Comment by eliseuegewarth** [comment]
@fepas @gdeusdara trabalhem na branch [194_fix_eslint](https://github.com/fga-gpp-mds/2018.1-Dulce_App/tree/194_fix_eslint) para a solução desta issue

**Comment by eliseuegewarth** [comment]
Critérios de aceitação desta issue:
- Correção de todos os problemas retornados pelo comando `npm run lint`
- Build do Travis continuar estável e funcionando.

**Comment by gdeusdara** [comment]
@egewarth @eliseuegewarth @gag2502 @alvesisaque gente, eu tive q fazer umas alterações que estavam quebrando a master ou estavam mal elaboradas, são elas

* correção dos inputs da pagina de login
* coloquei o redux para receber os dados do usuario na hora de logar para tê-los na pagina de editar
* mudei alguns placeholders de uns inputs q estavam em ingles
* nomes de variaveis que estavam em portugues

**Comment by eliseuegewarth** [comment]
Faça um pr para a Master. Mas isso é um HOTFIX de outras issues, não está relacionado exatamente a essa issue.

**Comment by gdeusdara** [comment]
foi a gabi que pediu pra fazer aqui
