### ISSUE TITLE
Planejamento da Release

### ISSUE THREAD

**Issue by alvesisaque** [fga-gpp-mds/2018.1-Dulce_App#202]
Durante a sprint 5, o time deverá se organizar para a release 2 e o encaminhamento para a finalização do projeto.
- Retrospectiva e Postmorten da release 1
- Definir o roadmap inicial para ajudar no planejamento
- Trocar informações entre o time

**Comment by alvesisaque** [comment]
Realizado na reunião de sábado, essa issue foi concluída.

**Comment by alvesisaque** [comment]
@egewarth, @gag2502, @eliseuegewarth devemos levar na reunião de quinta (27/04)o roadmap de papeis.

**Comment by gag2502** [comment]
@alvesisaque Beleza 👍

**Comment by alvesisaque** [comment]
Finalizado o roadmap do scrum master identificando o nível de maturidade desejado e como será feito no roadmap geral

**Comment by alvesisaque** [comment]
Essa isseu continuará como débito técnico pois o roadmap inicial não pode ser concluído, no inicio separado para fazer o roadmap por papeis e em seguida priorizar e definir as atividades do roadmap geral. isso não foi concluído pelo papel.

**Comment by alvesisaque** [comment]
Issue finalizada após uma reunião de EPS

**Comment by gag2502** [comment]
@alvesisaque Com esse planejamento , teremos maior maturidade para tomar decisões

**Comment by egewarth** [comment]
@gag2502 Com certeza Gaby, acho que devemos sentar dnv e validar oq fizemos e evoluir mais

**Comment by egewarth** [comment]
@egewarth Gostei muito do nosso rendimento, mesmo sendo poucas sprints, acho que pelo tempo que a gente tinha foi bem produtivo e deu uma visão boa do que devemos fazer

**Comment by gag2502** [comment]
@egewarth Verdade ... Acredito que com as funcionalidades bem planejadas , poderemos escolher um bom ferramental para oferecer a melhor experiência ao usuário do nosso produto

**Comment by egewarth** [comment]
@gag2502 Acho que além da experiência do usuário, o projeto em si faz mais sentido, é como se tivéssemos um caminho a ser seguido

**Comment by gag2502** [comment]
@egewarth Sim ... Agora o céu é o limite ...
