### ISSUE TITLE
HOTFIX Terminar a correção de erros encontrados

### ISSUE THREAD

**Issue by gabibguedes** [fga-gpp-mds/2018.1-Dulce_App#211]
- Colocar o ScrollView na tela de Editar perfil
- Colocar o fundo da tela inicial como branco

**Comment by gabibguedes** [comment]
Foi também arrumado pra ele pegar as informações do usuario logado nas telas de editar e visualizar perfil

**Comment by egewarth** [comment]
@gabibguedes , vc esqueceu de colocar a milestone isso é essencial. Faça o quanto antes, bjs
