### ISSUE TITLE
Treinamento sobre uso do GitHub e labels

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#245]
Nessa issue deve ser feito:

- [x] Ensinar como criar issues;
- [x] como e quais labels adicionar;
- [x] como pontuar;
- [x] melhor uso do ZenHub;
- [x] métricas zenhub;
- [x] roadmap;
- [x] linkar outro repositório.

**Comment by eliseuegewarth** [comment]
Vocês podem ver os boards do zenhub através do app do zenhub:
https://app.zenhub.com/workspace/o/fga-gpp-mds/2018.1-dulce_app/boards?repos=124531192,126094376
