### ISSUE TITLE
Treinamento sobre Scrum e XP

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#246]
Nessa issue deve ser feito:
- Ensinar como deve ser o pareamento;
- explicar praticas do scrum;
- explicar praticas do XP.

**Comment by alvesisaque** [comment]
Links uteis para a metodologia ágil https://pt.slideshare.net/ThoughtWorks?utm_campaign=profiletracking&utm_medium=sssite&utm_source=ssslideview
