### ISSUE TITLE
Remodelar documento de arquitetura com os novos requisitos

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#247]
Nessa issue deve ser feito:
- Remodelagem da arquitetura com os novos papéis;
- Rever modelagem da escala;
- Remodelagem da arquitetura com hospitais e setores.

**Comment by BeatrizHanae** [comment]
Boa noite, o que você quer dizer com rever a modelagem da escala? 
Novos atributos? Métodos? Ta errado a relação? Ou somente aquele negócio de escala para todos, não somente para os médicos?

**Comment by egewarth** [comment]
@BeatrizHanae A escala é feita de horários, a questão é desacoplar os horários da escala em uma nova classe apenas para horários, os requisitos para isso estão na história de criar horário de escala.
A escala em si é formada por horários

**Comment by egewarth** [comment]
@egewarth Alem dos horários a escala vai pertencer a um funcionário, vai conter os dados de setor e vai ter um somatório das horas completas pelo funcionário.

**Comment by egewarth** [comment]
@BeatrizHanae O supervisor creio que não poderá alterar, agora o gerente não tenho certeza, mas imagino que possam alterar sim
