### ISSUE TITLE
Treinamento API

### ISSUE THREAD

**Issue by gag2502** [fga-gpp-mds/2018.1-Dulce_App#252]
- Local : Hangout's Google
- Horário : 22h

O dado treinamento visa alinhar todos os membros ao novo código da API.
Conteúdo : 
- SenecaJs
- Como usar docker na API
- Database
- RabbitMQ
- Serviço 
  - Cliente 
    -  client_servico.js
    - api.js
  - Servidor
    - servico.js

**Comment by eliseuegewarth** [comment]
Advanced Message Queuing Protocol (AMQP)
