### ISSUE TITLE
Detalhamento dos novos requisitos

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#258]
Nessa issue deve ser feito:

- [ ] Detalhamento dos requisitos encontrados na issue [257](https://github.com/fga-gpp-mds/2018.1-Dulce_App/issues/257)
- [x] Priorização para sprint 7
- [x] Atualização do mapa de requisitos
- [ ] 1. Atualizar descrição dos épicos
- [ ] 2. Atualizar mindmap dos requisitos

**Comment by egewarth** [comment]
@fga-gpp-mds/eps-agr me ajudem com a pontuação.

**Comment by egewarth** [comment]
Issue com forte dependencia da #257.

**Comment by gdeusdara** [comment]
@egewarth acho q 1 ou 2

**Comment by egewarth** [comment]
@gdeusdara , é EPS meu querido
