### ISSUE TITLE
Analisar organograma da instituição 

### ISSUE THREAD

**Issue by gag2502** [fga-gpp-mds/2018.1-Dulce_App#259]
Ter uma visão geral de toda instituição para ter noção de setores e pessoas envolvidos.

**Comment by egewarth** [comment]
Qual instituição será considerada? 
Hospital do Gama?
Hospital da criança?
Sarah?

**Comment by gag2502** [comment]
@egewarth Acho que esses 3 ... E acho que 3 são suficientes

**Comment by egewarth** [comment]
@gag2502 Quais 3?

**Comment by gag2502** [comment]
@egewarth Sarah , Hospital da Criança e Hospital do Gama

**Comment by egewarth** [comment]
@gag2502 Ah só, vlw Gabi

**Comment by alvesisaque** [comment]
Hospital da criança 
http://www.hcb.org.br/institucional/organograma/
http://www.hcb.org.br/arquivos/downloads/organograma_site_hcb_novo_22_02_2018.pdf

Rede sul da secretaria de saúde (Gama e Santa Maria)
http://www.saude.df.gov.br/regiao-sul/
http://www.saude.df.gov.br/wp-conteudo/uploads/2018/02/p._SUL_10_ALTERACAO.pdf

**Comment by alvesisaque** [comment]
O hospital da criança conta com uma infraestrutura diferente da rede pública, mais focado na região sul do DF. 
O hospital da criança possui 6 macro áreas e dessas, 3 podem ser possível investigar e buscar auxilio sobre a acão do aplicativo Dulce. São elas: 

- Diretoria Administrativa (DIRAD) 
Coordenação de Tecnologia da Informação CTI

- Diretoria de Estratégia Inovação (DIREI)
Núcleo de Estatística e Controle NEC

- Diretoria de Recursos Humanos (DIRHU) 

- Diretoria do Corpo Clínico (DCLIN)

**Comment by alvesisaque** [comment]
A Rede publica de saúde do DF, mais especificamente a região sul do DF possui os seguintes pontos a se procurar em casos de necessidade de busca de informações:

- GERÊNCIA DE PESSOAS
Mais centralizado no NÚCLEO DE CONTROLE DE ESCALAS
