### ISSUE TITLE
Estudar viabilidade de ATDD 

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#265]
Nessa issue deve ser feito:
- Estudo das técnologias para implementação de Acceptance Tests
- Estudo de Acceptance Tests
- Estudo sobre ATDD
- Como implantar
- Tempo adicionado

**Comment by eliseuegewarth** [comment]
Olha que coisa maravilhosa! Já tem um link na wiki da disciplina sobre ATDD (e eu achei no Top 5 links do google):
https://github.com/fga-gpp-mds/A-Disciplina/wiki/Acceptance-Test-Driven-Development-(ATDD)

**Comment by eliseuegewarth** [comment]
@egewarth Não há essa necessidade. Na verdade ATDD é uma técnica que pode ser aplicada em qualquer cenário de projeto onde for possível a implementação de testes de aceitação. 
O ATDD pode ser implementado inicialmente com a escrita dos testes de aceitação em linguagem natural apenas, para criar o habito de escrever testes de aceitação.

**Comment by egewarth** [comment]
@eliseuegewarth Pra aplicar atdd precisa fazer Acceptance test. Como eu já comentei na issue existem algumas ferramentas pra fazer acceptance test automático, é a intenção do nosso atdd, fazer o test falhar se a pessoa não implementar do jeito correto

**Comment by egewarth** [comment]
@eliseuegewarth Como o TDD quebra os tests quando não está implementado da maneira correta

**Comment by eliseuegewarth** [comment]
@egewarth Este blog aqui ensina a fazer testes de aceitação com o Jest:
https://braziljs.org/blog/teste-de-aceitacao-com-react-jest-e-nightmare/
A principal vantagem pra gente é que já usamos o jest como ferramenta de testes no App, sendo necessária apenas a evolução do uso e adaptações do Test tool kit, adicionando o enzyme e o nightmare

**Comment by eliseuegewarth** [comment]
@eliseuegewarth Outro link util:
https://www.viget.com/articles/acceptance-testing-react-apps-with-jest-and-nightmare/

**Comment by egewarth** [comment]
@eliseuegewarth Exatamente isso que precisamos que vc faça.

**Comment by egewarth** [comment]
@eliseuegewarth Que recursivo você
