### ISSUE TITLE
Implementar ChatOps

### ISSUE THREAD

**Issue by eliseuegewarth** [fga-gpp-mds/2018.1-Dulce_App#277]
### Nessa issue será realizado:
- Estudo sobre ChatOps e suas principais características
- Analisar viabilidade de implementação
- Priorizar necessidades de ferramentas
- Artefato descrevendo brevemente os benefícios e a viabilidade técnica de ChatOps

#### Critérios de aceitação:
- [x] Descrever brevemente os benefícios de ChatOps
- [x] Descrevendo a viabilidade técnica de ChatOps
- [x] Lista priorizada de ferramentas de ChatOps

**Comment by eliseuegewarth** [comment]
links úteis:
- https://www.pagerduty.com/blog/what-is-chatops/

**Comment by eliseuegewarth** [comment]
https://hubot.github.com/docs/

**Comment by eliseuegewarth** [comment]
Travis CI bot para telegram:
@travisci_build_bot

**Comment by eliseuegewarth** [comment]
Git Releases bot para telegram:
@GithubReleasesBot

**Comment by eliseuegewarth** [comment]
Após pesquisar, encontrei ferramentas que buscam atacar o ChatOps como:
- https://hubot.github.com/
- https://www.lita.io/
- http://errbot.io

A mais notória destas ferramentas é o HuBot, desenvolvido pela GitHub e oferece uma boa integração com projetos da mesma.

Na atual situação do projeto, onde ainda encontramos algumas dificuldades em estabilizar o DevOps, o mais adequado é planejar a implementação do ChatOps na próxima release.

**Comment by egewarth** [comment]
@eliseuegewarth Aconselho implementar ao menos a integração com o github bot essa sprint para a API, tendo em vista que não está cadastrada

**Comment by egewarth** [comment]
@egewarth Minto, tá sim, desculpa

**Comment by eliseuegewarth** [comment]
Algumas integrações já são viáveis e podem ser implementadas para a próxima sprint.
Como o principal meio de comunicação da Equipe é o telegram pesquisei algumas integrações para as principais ferramentas em uso:
- @GitHubBot (Notificações sobre atualizações de commits e issues, Já em uso)
- @GithubReleasesBot (Notificações de lançamento de releases no GitHub, OBS: Não notifica sobre o lançamento de tags) 
- @travisci_build_bot (Notificações sobre status dos builds)

**Comment by eliseuegewarth** [comment]
Referencia sobre chatOps:
http://fernandonogueira.io/2015/07/27/chatops-comunicao-deployments-rpidos-times-satisfeitos.html

**Comment by eliseuegewarth** [comment]
Para esclarecer melhor:
ChatOps != ChatBots
ChatOps faz uso de ChatBots e outras várias customizações  na organização do projeto.
Em alguns exemplos descritos no ultimo link, faz-se o uso do HuBot para comandar uma operação de deploy via chat e o HuBot inicia a tarefa no servidor e vai passando o feedback do status da operação no canal de comunicação entre o desenvolvedor e o HuBot.
Essas customizações podem levar um certo tempo e devemos focar nossos esforços em estabilizar os papéis antes de atacar estas melhorias de projeto.

**Comment by eliseuegewarth** [comment]
Com os três bots para telegram (citados acima), já poderemos ter um feedback melhor sobre o status do projeto, sem gastar muito tempo. Podemos encerrar o escopo desta issue nas integrações citadas?
@alvesisaque @egewarth @gag2502

**Comment by alvesisaque** [comment]
@eliseuegewarth Sim

**Comment by eliseuegewarth** [comment]
OK então. Vou encerrar a issue.
Em momento oportuno priorizaremos a implementação de alguma das ferramentas de ChatOps.
