### ISSUE TITLE
Automatizar empacotamento de versão do projeto

### ISSUE THREAD

**Issue by eliseuegewarth** [fga-gpp-mds/2018.1-Dulce_App#279]
Nessa issue será realizado:
- Definir data/hora para disparar a tarefa
- Incrementar versão automaticamente
- Adicionar informações de _Release notes_ da versão empacotada

Critérios de aceitação:
- [ ] lançamento automático e programado de versões
- [ ] Compatibilizar com deploy contínuo

**Comment by gag2502** [comment]
@eliseuegewarth Eita kkkk essa issue é sem dúvida uma das mais difíceis

**Comment by eliseuegewarth** [comment]
Ainda não tenho certeza de como vou fazer isso (de verdade)
Provavelmente vai ter um repositório separado só para esse mini DevOps.
