### ISSUE TITLE
Criar usuário gestor

### ISSUE THREAD

**Issue by egewarth** [fga-gpp-mds/2018.1-Dulce_App#60]
História:
Eu, como **gestor** desejo **criar uma conta** a fim de **logar no app**.

Critérios de aceitação:
Ler dados do gestor no formulário
- Nome
- Matricula
- Setor
- Senha
- Hospital

Validar dados do gestor
- Todos do formulário

Enviar dados do gestor pra API
- Todos do formulário

**Comment by gdeusdara** [comment]
@egewarth @eliseuegewarth @alvesisaque gente, a gnt vai usar qual ferramenta de teste?? tem a Jest, q é a q ta documentada no site da React-native (parece ser de boa) ou aquela outra q o cara falou? Enzyme

**Comment by egewarth** [comment]
https://github.com/fga-gpp-mds/agr-react-native/blob/master/CONTRIBUTING.md#work-in-progress

**Comment by gag2502** [comment]
@BeatrizHanae Por que vocês acham que daria conflitos ??? Tem na política de branches falando sobre como resolver essa programação em paralelo aí gente ... Olhem lá

**Comment by BeatrizHanae** [comment]
@fga-gpp-mds/agr-app Então, mas e ai? O procedimento correto seria tudo para master né? Expliquem me melhor, por favor...

**Comment by alvesisaque** [comment]
Então, vocês devem criar a pasta, subir para a master e as outras equipes devem atualizar as suas respectivas branchs com a master.

Lembrem-se: todas as branchs devem ser criadas a partir da master para não dar conflito, nunca atualizar a sua branch com a do coleguinha!

**Comment by alvesisaque** [comment]
Sigam o guia de contribuição para fazer esse processo corretamente!

**Comment by egewarth** [comment]
@BeatrizHanae Seguinte, no guia de contribuição tem um típico chamado work in progress (link da última resposta), que é quando você tá fazendo algo que todos precisam disso, você vai abrir um pull request com o nome WIP número da issue e descrição, WIP significa work um progress, esse PR vai ser aceito e vai pra master, todos atualizam a branch com o pull --rebase da master e continuem o trabalho, ao final de tudo abre o PR dnv sem o WIP e o mestre é feito normalmente.
No caso de vocês agora...
Vocês vão criar as 2 pastas certo?
Todos precisam dessas 2 pastas certo?
Os arquivos de dentro dessa pasta vão conter os mesmos nomes ou vão ser arquivos diferentes? Se forem arquivos diferentes não haverá conflito, por mais que as pastas sejam criadas em ambos brachs, daí não há necessidade do WIP. Caso os arquivos tiverem nomes iguais, provavelmente vai dar conflito e um merge manual deverá ser feito OU, vocês façam o PR com WIP e tudo certo

**Comment by BeatrizHanae** [comment]
Melhorou mil vezes para o meu entendimento e dos meus colegas, obrigada :D

**Comment by egewarth** [comment]
@BeatrizHanae Qual o caso de vocês? WIP ou sem conflito?

**Comment by BeatrizHanae** [comment]
@egewarth WIP, porque as pastas serão padrão em todas as branchs do CRU...logo precisamos atualizar as pastas na master, para que possamos usar em branchs separadas. Até por questão de organização! hahahaha

**Comment by gabibguedes** [comment]
@egewarth e @BeatrizHanae  Não há apenas pastas, tem o arquivo das rotas que é o mesmo e será modificado por todos

**Comment by eliseuegewarth** [comment]
@gabibguedes para o caso de arquivos "compartilhados", ao final do trabalho de cada dupla (commits já na master) as próximas duplas terão de fazer o rebase, resolver os conflitos gerados e atualizar seus PRs.

**Comment by egewarth** [comment]
@eliseuegewarth Isso ocorreria mesmo com a devel

**Comment by eliseuegewarth** [comment]
@fga-gpp-mds/mds-agr
 **Não tenham** (muito) **medo** de conflitos do git. **Conflitos** são comuns em projetos com **muitos** desenvolvedores **ativos** e **geralmente** são **fáceis** de resolver.

**Comment by eliseuegewarth** [comment]
@gdeusdara 
Talvez o mais adequado seja utilizar o Jest neste primeiro momento, pelo suporte da documentação do próprio react-native.
