### ISSUE TITLE
Reunião de Duvidas com a Cristiane

### ISSUE THREAD

**Issue by alvesisaque** [fga-gpp-mds/2018.1-Dulce_App#94]
- 29/03
- 9:00
- iTrack

**Comment by alvesisaque** [comment]
Duvidas sobre o burndown de riscos

**Comment by alvesisaque** [comment]
Reunião cancelada pela Professora

**Comment by gag2502** [comment]
Reunião cancelada pela professora, e e-mail para remarcar a reunião não respondido.
