### ISSUE TITLE
Reunião com Colaboradores externos

### ISSUE THREAD

**Issue by alvesisaque** [fga-gpp-mds/2018.1-Dulce_App#95]
- Auxilio na definição da logo do aplicativo
- Divulgação do projeto nas mídias sociais 
Data: 30/03
Localização: Village

**Comment by fepas** [comment]
A logo que eu fiz já está na branch de protótipo! Qualquer problema me marque nessa issue.

**Comment by eliseuegewarth** [comment]
A tarefa não foi encerrada e ainda sera executada em outro momento.

**Comment by eliseuegewarth** [comment]
Pagina do aplicativo no facebook:
https://www.facebook.com/dulceaplicativo/
